# -*- coding: utf-8 -*-
"""traffic_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ncP54s1zI0YLjmiPWBdsfxUvtJZq5aPT
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import random
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler

# 連接到雲端硬碟
from google.colab import drive
drive.mount('/content/drive')

# 1. 實驗重現性設定
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)

set_seed(42)

# 2. 超參數調整
TIME_STEPS = 24
BATCH_SIZE = 32
EPOCHS = 15
BASE_LR = 0.007

# 3. data process
df = pd.read_csv("/content/drive/MyDrive/dl_github_open_source/Metro_Interstate_Traffic_Volume.csv")
df['date_time'] = pd.to_datetime(df['date_time'])
df = df.sort_values('date_time').reset_index(drop=True)

# time period engineering
df['hr_sin'] = np.sin(2 * np.pi * df['date_time'].dt.hour / 24)
df['hr_cos'] = np.cos(2 * np.pi * df['date_time'].dt.hour / 24)
df['day_sin'] = np.sin(2 * np.pi * df['date_time'].dt.weekday / 7)
df['day_cos'] = np.cos(2 * np.pi * df['date_time'].dt.weekday / 7)
df['is_peak'] = df['date_time'].dt.hour.isin([7,8,9,16,17,18]).astype(int)

# one-hot encoding
df = pd.get_dummies(df, columns=['holiday', 'weather_main'])

target = 'traffic_volume'
features = [f for f in df.select_dtypes(include=[np.number, 'bool']).columns if f != target]

# data normalize
scaler_X, scaler_y = MinMaxScaler(), MinMaxScaler()
X_scaled = scaler_X.fit_transform(df[features])
y_scaled = scaler_y.fit_transform(df[[target]])

Y_MIN, Y_MAX = float(scaler_y.data_min_[0]), float(scaler_y.data_max_[0])

# 滑動窗口函數
def create_sequences(X, y, time_steps):
    Xs, ys = [], []
    for i in range(len(X) - time_steps):
        Xs.append(X[i:(i + time_steps)])
        ys.append(y[i + time_steps])
    return np.array(Xs), np.array(ys)

X_seq, y_seq = create_sequences(X_scaled, y_scaled, TIME_STEPS)

split = int(len(X_seq) * 0.8)
X_train, X_test = X_seq[:split], X_seq[split:]
y_train, y_test = y_seq[:split], y_seq[split:]

# 4. 自定義指標
@tf.keras.utils.register_keras_serializable(package="Custom")
class TrafficAccuracy(tf.keras.metrics.Metric):
    def __init__(self, threshold=500, y_min=0.0, y_max=1.0,
                 name='traffic_acc_500', **kwargs):
        super().__init__(name=name, **kwargs)
        self.threshold = float(threshold)
        self.y_min = float(y_min)
        self.y_max = float(y_max)
        self.correct = self.add_weight(name='correct', initializer='zeros')
        self.total = self.add_weight(name='total', initializer='zeros')

    def update_state(self, y_true, y_pred, sample_weight=None):
        y_t_real = y_true * (self.y_max - self.y_min) + self.y_min
        y_p_real = y_pred * (self.y_max - self.y_min) + self.y_min
        is_correct = tf.cast(tf.abs(y_t_real - y_p_real) <= self.threshold,
                             tf.float32)
        self.correct.assign_add(tf.reduce_sum(is_correct))
        self.total.assign_add(tf.cast(tf.size(y_true), tf.float32))

    def result(self):
        return tf.math.divide_no_nan(self.correct, self.total)

    def reset_state(self):
        self.correct.assign(0.0)
        self.total.assign(0.0)

    def get_config(self):
        config = super().get_config()
        config.update({
            'threshold': self.threshold,
            'y_min': self.y_min,
            'y_max': self.y_max
        })
        return config

    @classmethod
    def from_config(cls, config):
        return cls(**config)

# 5. 模型架構
inputs = tf.keras.Input(shape=(TIME_STEPS, X_train.shape[2]))
c1 = tf.keras.layers.Conv1D(64, 3, padding='same', activation='relu')(inputs)
c2 = tf.keras.layers.Conv1D(64, 5, padding='same', activation='relu')(inputs)
merged = tf.keras.layers.Concatenate()([c1, c2])
bn = tf.keras.layers.BatchNormalization()(merged)

lstm_out = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(128))(bn)
drop = tf.keras.layers.Dropout(0.3)(lstm_out)

d1 = tf.keras.layers.Dense(256, activation='relu')(drop)
d2 = tf.keras.layers.Dense(64, activation='relu')(d1)
outputs = tf.keras.layers.Dense(1)(d2)

model = tf.keras.Model(inputs=inputs, outputs=outputs)

# 6. 訓練策略(學習率調整)
def lr_schedule(epoch):
    if epoch < 5: return BASE_LR
    if epoch < 12: return BASE_LR * 0.3
    return BASE_LR * 0.05

lr_cb = tf.keras.callbacks.LearningRateScheduler(lr_schedule)

#印出model summary
model.summary()

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=BASE_LR),
    loss=tf.keras.losses.Huber(delta=0.5),
    metrics=[TrafficAccuracy(threshold=500, y_min=Y_MIN, y_max=Y_MAX),'mae','mse'])

# 7. 執行訓練
history = model.fit(
    X_train, y_train,
    validation_split=0.1,
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    callbacks=[lr_cb],
    verbose=1
)

# 存檔模型
import joblib
import json

model.save("/content/drive/MyDrive/dl_github_open_source/traffic_model/traffic_model.keras")
joblib.dump(scaler_X, "/content/drive/MyDrive/dl_github_open_source/traffic_model/traffic_model_scaler_X.pkl")
joblib.dump(scaler_y, "/content/drive/MyDrive/dl_github_open_source/traffic_model/traffic_model_scaler_y.pkl")
with open('/content/drive/MyDrive/dl_github_open_source/traffic_model/traffic_history.json', 'w') as f:
    json.dump(history.history, f)